name: eaipchinaviewer
description: EAIP China Viewer App
publish_to: 'none'
version: 1.5.0+8  # 从 1.3.5+6 更新到 1.5.0+8

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1  # 已有
  webview_windows: ^0.3.0  # 添加 Windows Webview 支持
  crypto: ^3.0.3
  pointycastle: ^3.7.4
  asn1lib: ^1.5.0
  flutter_cached_pdfview: ^0.4.2  # 添加这一行
  open_file: ^3.3.2  # 添加这一行，用于打开PDF文件
  webview_flutter: ^4.7.0  # 添加这一行
  flutter_pdfview: ^1.3.2
  intl: ^0.19.0  # 添加这一行
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2
  flutter_markdown: ^0.6.20
  package_info_plus: ^5.0.1  # 添加这一行

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/privacy_policy.md
    - assets/terms_of_service.md

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
        - asset: assets/fonts/NotoSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansSC-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"
